/* race.c — unity master for the race module.
 *
 * Mechanically generated by decomp/tools/gen_shim.py
 * --rebuild-master race. Each #include below pulls in one
 * prod TU's worth of decomp source, ordered by prod address so
 * that source order in this file determines link order in
 * race.bin — we do not depend on linker SORT_BY_NAME.
 *
 * As prod TUs are brought in (initially as 100% naked asm
 * shims, later lifted to ordinary C), regenerate this file
 * with the script above. Hand edits will be lost.
 *
 * Compiled by saturncc:
 *
 *   make race.s
 *
 * (See decomp/Makefile for the full pipeline.)
 */

#include "FUN_06028000.c"
#include "FUN_06029810.c"
#include "FUN_06029998.c"
#include "FUN_06029A78.c"
#include "FUN_06029CA0.c"
#include "FUN_06029D8C.c"
#include "FUN_0602B22C.c"
#include "FUN_060324E8.c"
#include "FUN_06032E44.c"
#include "FUN_06033DC8.c"
#include "FUN_060351CC.c"
#include "FUN_0603B6FC.c"
#include "FUN_0603B940.c"
#include "FUN_0603C304.c"
#include "FUN_0604025C.c"
#include "FUN_0604256C.c"
#include "FUN_0604264C.c"
#include "FUN_06042998.c"
#include "FUN_06042C64.c"
#include "FUN_06042DC4.c"
#include "FUN_060433F0.c"
#include "FUN_06043460.c"
#include "FUN_060434D0.c"
#include "FUN_06043630.c"
#include "FUN_060436D0.c"
#include "FUN_06043748.c"
#include "FUN_06043810.c"
#include "FUN_06043854.c"
#include "FUN_060438C8.c"
#include "FUN_06043934.c"
#include "FUN_0604398C.c"
#include "FUN_060439F4.c"
#include "FUN_06043C20.c"
#include "FUN_06043CCC.c"
#include "FUN_06044060.c"
#include "FUN_06047DF0.c"
#include "FUN_06048278.c"
#include "FUN_0604C76C.c"
#include "FUN_0604D380.c"
