#!/usr/bin/env python3
"""gen_shim.py — generate a naked asm-shim .c from a prod .s.

For the unity-build bring-in. Each prod TU under
src/<module>/FUN_<addr>.s gets translated to a
decomp/<module>/FUN_<addr>.c that wraps the prod assembly
in `int FUN_<addr>(void) asm { ... }`. Stage 4 of the
asm-shim mechanism in saturncc emits the body verbatim,
producing byte-identical .o output.

Usage:
    gen_shim.py <module> <FUN_addr>            # gen one shim
    gen_shim.py <module> --rebuild-master      # regenerate <module>.c

    <module>      e.g. "race"
    <FUN_addr>    e.g. "FUN_06029CA0"

The script lives at decomp/tools/ and reads/writes paths
relative to the project root (decomp/ and src/ siblings).

Translation rules:
  * Drop framing lines: .section / .global / .type / file-scope
    /* comment */ headers — saturncc emits its own framing per
    Stage 4. The first `FUN_<addr>:` entry label is also dropped;
    saturncc emits the function label.
  * Everything from the line AFTER the entry label through the
    last byte of the file becomes the asm{} body.
  * For multi-entry TUs (multiple `FUN_<addr>:` labels — Cat 1
    fall-through pattern), this MVP errors out. Multi-entry
    handling is a separate workstream.
  * The first decompiled function's signature is `int FUN_<addr>(void)`.
    Internal callees / DATs / sym_ references stay as-is in the asm
    body — the linker resolves them via race.ld's PROVIDE() chain.

Master regeneration:
  Walks decomp/<module>/FUN_*.c, sorts by hex address, rewrites
  decomp/<module>/<module>.c with #include directives in address-
  ascending order so source order = link order.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
DECOMP = ROOT / "decomp"
PROD_SRC = ROOT / "src"

ENTRY_LABEL_RE = re.compile(r"^([A-Za-z_][\w]*?):\s*$")
FUN_NAME_RE = re.compile(r"^FUN_[0-9A-Fa-f]+$")
DROP_DIR_RE = re.compile(r"^\s*\.(section|global|globl|type)\b")


def shim_header(fun_name, prod_rel_path):
    return f"""/* {fun_name} — naked asm shim, mechanically generated.
 *
 * Source: {prod_rel_path}
 * Generator: decomp/tools/gen_shim.py
 *
 * Body emitted verbatim via saturncc Stage 4 naked asm-shim emit.
 * Prod's own framing (.section / .global / .type / entry label)
 * is dropped — saturncc emits its own framing per Stage 4. The
 * function and any trailing literal pool / data table inside its
 * section are wrapped in a single asm{{}} block.
 */

int {fun_name}(void) asm {{
"""


def gen_one(module, fun_name):
    prod_path = PROD_SRC / module / f"{fun_name}.s"
    if not prod_path.exists():
        sys.exit(f"error: prod source not found: {prod_path}")

    text = prod_path.read_text(encoding="utf-8")
    lines = text.splitlines()

    # Find the primary entry label `<FUN_NAME>:`. The body is
    # everything after it — including any subsequent
    # `.global FUN_<other>` + `FUN_<other>:` co-located entries
    # (Cat 1 multi-entry pattern). Those embedded entries become
    # bare-named labels inside the shim's asm body, which is the
    # correct shape for callers that bsr/jsr to them by their
    # prod address-derived names.
    entry_idx = None
    for i, ln in enumerate(lines):
        m = ENTRY_LABEL_RE.match(ln)
        if m and m.group(1) == fun_name:
            entry_idx = i
            break
    if entry_idx is None:
        sys.exit(f"error: no `{fun_name}:` entry label found in {prod_path}")

    body_lines = lines[entry_idx + 1:]
    # Trim trailing empty lines.
    while body_lines and body_lines[-1].strip() == "":
        body_lines.pop()

    out_path = DECOMP / module / f"{fun_name}.c"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    prod_rel = prod_path.relative_to(ROOT).as_posix()
    out_text = shim_header(fun_name, prod_rel)
    for ln in body_lines:
        out_text += ln + "\n"
    out_text += "}\n"
    out_path.write_text(out_text, encoding="utf-8")
    print(f"  wrote {out_path.relative_to(ROOT).as_posix()} ({len(body_lines)} body lines)")


def rebuild_master(module):
    mod_dir = DECOMP / module
    if not mod_dir.exists():
        sys.exit(f"error: {mod_dir} does not exist")

    shims = sorted(mod_dir.glob("FUN_*.c"))
    if not shims:
        sys.exit(f"error: no FUN_*.c files in {mod_dir}")

    # Sort by hex address for prod-link-order #includes.
    def addr_key(p):
        return int(p.stem.split("_")[1], 16)
    shims.sort(key=addr_key)

    master_path = mod_dir / f"{module}.c"
    out = f"""/* {module}.c — unity master for the {module} module.
 *
 * Mechanically generated by decomp/tools/gen_shim.py
 * --rebuild-master {module}. Each #include below pulls in one
 * prod TU's worth of decomp source, ordered by prod address so
 * that source order in this file determines link order in
 * {module}.bin — we do not depend on linker SORT_BY_NAME.
 *
 * As prod TUs are brought in (initially as 100% naked asm
 * shims, later lifted to ordinary C), regenerate this file
 * with the script above. Hand edits will be lost.
 *
 * Compiled by saturncc:
 *
 *   make {module}.s
 *
 * (See decomp/Makefile for the full pipeline.)
 */

"""
    for s in shims:
        out += f'#include "{s.name}"\n'
    master_path.write_text(out, encoding="utf-8")
    print(f"  wrote {master_path.relative_to(ROOT).as_posix()} ({len(shims)} shims)")


def main():
    ap = argparse.ArgumentParser(description="generate naked asm-shim .c from prod .s")
    ap.add_argument("module", help="module name, e.g. 'race'")
    ap.add_argument("fun_name", nargs="?",
                    help="FUN_<addr> to generate; omit when using --rebuild-master")
    ap.add_argument("--rebuild-master", action="store_true",
                    help="regenerate <module>/<module>.c from existing FUN_*.c shims")
    args = ap.parse_args()

    if args.rebuild_master:
        if args.fun_name:
            sys.exit("error: --rebuild-master takes no FUN_<addr>")
        rebuild_master(args.module)
        return
    if not args.fun_name:
        sys.exit("error: missing FUN_<addr> (or pass --rebuild-master)")
    if not FUN_NAME_RE.match(args.fun_name):
        sys.exit(f"error: '{args.fun_name}' is not FUN_<hex>")
    gen_one(args.module, args.fun_name)


if __name__ == "__main__":
    main()
