#ifndef DUSA_STATE_H
#define DUSA_STATE_H
/* DUSA embedded-transplant state block + glue accessors (Phase D).
 * State lives in the COL dense body (LWR, disc-loaded + zeroed by
 * gen_disc_data.py) -- the 40-car shadow array is too big for any HWR gap.
 * C glue uses stack locals + .rodata consts only; no mutable globals
 * (.data/.bss are discarded by race_c.ld).
 *
 * COL body layout (guest = 0x00220000 + COL file offset; COL loads at 0x00220000
 * for every track), PACKED -- no gaps. The homed DUSA COL regions come from
 * tools/dusa_homing_map.py; offsets are COMPUTED + emitted by
 * `gen_disc_data.py --dryrun` (the source of truth); a disc build verifies this
 * header matches. Small hot static tables (gear/traction/drift/anim/F270 bounds)
 * are NOT here -- they were homed into race.bin (race.bin data shims). What lives
 * in COL: the big surface block, the LWR trig LUTs (cos/atan), and the runtime
 * work-RAM globals (pads/buttons/opponents/dispatch/scratch).
 *   0x00228000  DUSA_SHADOW_CARS 0x6140  shadow car structs (40 x 0x268 + slack)
 *   0x0022E140  DUSA_GLOBALS     0x400   CCE-side scaffolding scratch + faked inputs
 *   0x0022E540  DUSA_SURFACE     0x22D0  surface-writer curves + index (call 11)
 *   0x00230810  DUSA_COS_TABLE   0x4000  cos/sin LUT (LWR-resident)
 *   0x00234810  DUSA_ATAN_TABLE  0x2000  arctan LUT (LWR-resident; zeroed reserve)
 *   0x00236810  DUSA_PAD_BLOCK   0x1B4   pad state + init global + raw pad
 *   0x002369C4  DUSA_SURF_BUF    0x10    surface-type scratch buffer
 *   0x002369D4  DUSA_CAR_BLOCK   0x1A4   car-ptr + opponents + dispatch (mirror)
 *   0x00236B78  DUSA_ANIM_SCRATCH 0x10   anim cursor + anim scratch (written)
 *   0x00236B88  DUSA_BTN_BLOCK   0x10    button/input bit table
 *   0x00236B98  DUSA_ECF2_FLAG   0x8     ECF2 per-frame input flag (written)
 *   0x00236BA0  DUSA_LWR_GLOBAL  0x8     resident-kernel global read by CA84
 *   0x00236BA8  DUSA_TRACK_TABLES variable  per-track waypoints+segments (Step 6) */

/* CCE render car array (bridge write target) */
#define CCE_CAR_BASE        0x0605224C
#define CCE_CAR_STRIDE      0x1D8

/* DUSA shadow car array (bridge read source) */
#define DUSA_SHADOW_CARS    0x00228000
#define DUSA_SHADOW_STRIDE  0x268
#define DUSA_CAR_COUNT      40

#define DUSA_GLOBALS        0x0022E140

/* Homed DUSA COL regions (absolute LWR literals; ported asm references these by
 * macro + offset). KEEP IN SYNC with gen_disc_data.py / tools/dusa_homing_map.py
 * -- run `gen_disc_data.py --dryrun` to refresh; a disc build verifies the match.
 * Per-function reloc allowlists are regenerated by tools/gen_dusa_allowlists.py. */
#define DUSA_SURFACE        0x0022E540   /* surface curves + index; APROG slice (call 11) */
#define DUSA_COS_TABLE      0x00230810   /* cos/sin LUT; captured (file 0x10810) */
#define DUSA_ATAN_TABLE     0x00234810   /* arctan LUT; zeroed reserve until captured */
#define DUSA_PAD_BLOCK      0x00236810   /* pad state + init global (W) + raw pad; zeroed */
#define DUSA_SURF_BUF       0x002369C4   /* surface-type scratch buffer; zeroed */
#define DUSA_CAR_BLOCK      0x002369D4   /* car-ptr + opponents + dispatch, one mirror */
#define DUSA_ANIM_SCRATCH   0x00236B78   /* anim cursor + anim scratch (written); zeroed */
#define DUSA_BTN_BLOCK      0x00236B88   /* button/input bit table; zeroed */
#define DUSA_ECF2_FLAG      0x00236B98   /* ECF2 input flag (written); seeded from APROG */
#define DUSA_LWR_GLOBAL     0x00236BA0   /* resident-kernel global read by CA84; zeroed */

/* Per-track DUSA track data (waypoints + segments), placed AFTER the fixed/shared
 * regions. Variable size per track; each fits in its own COL (Three Seven ~13 KB,
 * Seaside ~161 KB). Reservation only until the Step-6 embed populates it. */
#define DUSA_TRACK_TABLES   0x00236BA8

/* Phase-D scaffolding scratch (throwaway; replaced at Step 1) */
#define DUSA_SCHED_PHASE    0x0022E140   /* u32: scheduler phase */
#define DUSA_SEED_FLAG      0x0022E148   /* u32: one-shot seed flag */
#define DUSA_SEED_X         0x0022E14C   /* s32: X captured at seed (wobble anchor) */
#define DUSA_STUB_TICK      0x0022E150   /* u32: stub tick counter */

/* Faked driving inputs (velocity + heading). Live-pokeable; seeded on the first
 * tick, read each frame, until the ECF2 dispatcher takes over (drops these). */
#define DUSA_STEP1_SPEED    0x0022E180   /* u32: faked velocity -> car[+0x0C] */
#define DUSA_STEP1_HEADING  0x0022E184   /* u32: hardcoded heading (16-bit angle) */

/* Dispatcher globals we OWN (option B): the ported dispatcher (ECF2) + the
 * functions that fetch the car reference DUSA work-RAM globals; we relocate those
 * pool words to these slots INSIDE the DUSA_CAR_BLOCK mirror so the pipeline runs
 * on OUR shadow car + OUR dispatch state, never touching CCE's live globals.
 *   DUSA_CAR_PTR     <- DUSA 0x0607E944 (car-pointer global; seed = shadow car)
 *   DUSA_DISP_STATE  <- DUSA 0x0607EAE4 (dispatch state index; seed = 0)
 *   DUSA_DISP_SCRATCH<- DUSA 0x0607EAC8 (per-frame scratch zeroed by ECF2) */
#define DUSA_CAR_PTR        0x002369D4   /* DUSA_CAR_BLOCK + 0x0 */
#define DUSA_DISP_SCRATCH   0x00236B58   /* DUSA_CAR_BLOCK + 0x184 */
#define DUSA_DISP_STATE     0x00236B74   /* DUSA_CAR_BLOCK + 0x1A0 */

/* volatile guest-RAM accessors */
#define DUSA_U32(addr) (*(volatile unsigned int   *)(addr))
#define DUSA_U16(addr) (*(volatile unsigned short *)(addr))

void dusa_bridge(void);
void dusa_frame(void);
void dusa_call_player(void);   /* asm trampoline: r0/r14=shadow car -> position writer */
void dusa_call_ecf2(void);     /* asm trampoline: real ECF2 dispatcher (reads car-ptr/state) */

/* Host-log debug primitive (trapa #0xFF; PATCHED-MEDNAFEN ONLY). -DDUSA_LOG
 * compiles it in; off -> DLOG() vanishes (no string/.rodata/trapa emitted). */
#ifdef DUSA_LOG
int dusa_log(const char *fmt, int a0, int a1, int a2);
#define DLOG(fmt, a, b, c)  dusa_log((fmt), (a), (b), (c))
#else
#define DLOG(fmt, a, b, c)  ((void)0)
#endif

#endif /* DUSA_STATE_H */
