/* FUN_0602FA98  0x0602FA98 */


/* WARNING: Control flow encountered bad instruction data */

void FUN_0602fa98(void)

{
  int iVar1;
  undefined4 uVar2;
  uint in_sr;
  int unaff_gbr;
  int in_vbr;
  
  (**(code **)(in_vbr + 0xec))();
  (**(code **)(in_vbr + 0x10c))();
  (**(code **)(in_vbr + 300))();
  (**(code **)(in_vbr + 0x14c))();
  (**(code **)(in_vbr + 0x16c))();
  (**(code **)(in_vbr + 0x18c))();
  (**(code **)(in_vbr + 0x1ac))();
  (**(code **)(in_vbr + 0x1d0))();
  (**(code **)(in_vbr + 0x1f0))();
  (**(code **)(in_vbr + 0x210))();
  (**(code **)(in_vbr + 0x230))();
  (**(code **)(in_vbr + 0x250))();
  (**(code **)(in_vbr + 0x274))();
  (**(code **)(in_vbr + 0x294))();
  (**(code **)(in_vbr + 0x2b4))();
  (**(code **)(in_vbr + 0x2d8))();
  (**(code **)(in_vbr + 0x2f8))();
  (**(code **)(in_vbr + 0x31c))();
  (**(code **)(in_vbr + 0x33c))();
  (**(code **)(in_vbr + 0x360))();
  (**(code **)(in_vbr + 0x380))();
  (**(code **)(in_vbr + 0x3a4))();
  (**(code **)(in_vbr + 0x3c8))();
  (**(code **)(in_vbr + 1000))();
  in_sr = in_sr & 0xfffffffe;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 2;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x12;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x21;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x30;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x3f;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x4f;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x5e;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x6d;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x7d;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x8c;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x9c;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0xab;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0xbb;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0xca;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0xda;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0xea;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0xf9;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 9;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x19;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x28;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x38;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x48;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x58;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x68;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x78;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x87;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0x97;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0xa7;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0xb7;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 200;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0xd8;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0xe8;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) & 0xf8;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 8;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0x18;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0x28;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0x39;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0x49;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0x59;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0x6a;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0x7a;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0x8a;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0x9b;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0xab;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0xbc;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0xcc;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0xdd;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0xed;
  *(byte *)(unaff_gbr + 0xff) = *(byte *)(unaff_gbr + 0xff) | 0xfe;
  iVar1 = iRam06030038;
  *(byte *)(unaff_gbr + iRam06030038) = *(byte *)(unaff_gbr + iRam06030038) | 0xfe;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0xed;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0xdd;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0xcc;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0xbc;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0xab;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0x9b;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0x8a;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0x7a;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0x6a;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0x59;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0x49;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0x39;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0x28;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 0x18;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) | 8;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0xf8;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0xe8;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0xd8;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 200;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0xb7;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0xa7;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x97;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x87;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x78;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x68;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x58;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x48;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x38;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x28;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x19;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 9;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0xf9;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0xea;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0xda;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0xca;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0xbb;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0xab;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x9c;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x8c;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x7d;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x6d;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x5e;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x4f;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x3f;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x30;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x21;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 0x12;
  *(byte *)(unaff_gbr + iVar1) = *(byte *)(unaff_gbr + iVar1) & 2;
  iVar1 = iRam060305cc;
  *(uint *)(iRam060305cc + -4) = in_sr;
  *(undefined4 *)(iVar1 + -8) = 0x60303be;
  (**(code **)(in_vbr + 1000))(0xfffffffe,0xfffffffa,0xfffffff8,0xfffffff7);
  *(uint *)(iVar1 + -0xc) = in_sr;
  *(undefined4 *)(iVar1 + -0x10) = 0x60303c2;
  (**(code **)(in_vbr + 0x3c8))();
  *(uint *)(iVar1 + -0x14) = in_sr;
  *(undefined4 *)(iVar1 + -0x18) = 0x60303c6;
  (**(code **)(in_vbr + 0x3a4))();
  *(uint *)(iVar1 + -0x1c) = in_sr;
  *(undefined4 *)(iVar1 + -0x20) = 0x60303ca;
  (**(code **)(in_vbr + 0x380))();
  *(uint *)(iVar1 + -0x24) = in_sr;
  *(undefined4 *)(iVar1 + -0x28) = 0x60303ce;
  (**(code **)(in_vbr + 0x360))();
  *(uint *)(iVar1 + -0x2c) = in_sr;
  *(undefined4 *)(iVar1 + -0x30) = 0x60303d2;
  (**(code **)(in_vbr + 0x33c))();
  *(uint *)(iVar1 + -0x34) = in_sr;
  *(undefined4 *)(iVar1 + -0x38) = 0x60303d6;
  (**(code **)(in_vbr + 0x31c))();
  *(uint *)(iVar1 + -0x3c) = in_sr;
  *(undefined4 *)(iVar1 + -0x40) = 0x60303da;
  (**(code **)(in_vbr + 0x2f8))();
  *(uint *)(iVar1 + -0x44) = in_sr;
  *(undefined4 *)(iVar1 + -0x48) = 0x60303de;
  (**(code **)(in_vbr + 0x2d8))();
  *(uint *)(iVar1 + -0x4c) = in_sr;
  *(undefined4 *)(iVar1 + -0x50) = 0x60303e2;
  (**(code **)(in_vbr + 0x2b4))();
  *(uint *)(iVar1 + -0x54) = in_sr;
  *(undefined4 *)(iVar1 + -0x58) = 0x60303e6;
  (**(code **)(in_vbr + 0x294))();
  *(uint *)(iVar1 + -0x5c) = in_sr;
  *(undefined4 *)(iVar1 + -0x60) = 0x60303ea;
  (**(code **)(in_vbr + 0x274))();
  *(uint *)(iVar1 + -100) = in_sr;
  *(undefined4 *)(iVar1 + -0x68) = 0x60303ee;
  (**(code **)(in_vbr + 0x250))();
  *(uint *)(iVar1 + -0x6c) = in_sr;
  *(undefined4 *)(iVar1 + -0x70) = 0x60303f2;
  (**(code **)(in_vbr + 0x230))();
  *(uint *)(iVar1 + -0x74) = in_sr;
  *(undefined4 *)(iVar1 + -0x78) = 0x60303f6;
  (**(code **)(in_vbr + 0x210))();
  *(uint *)(iVar1 + -0x7c) = in_sr;
  *(undefined4 *)(iVar1 + -0x80) = 0x60303fa;
  (**(code **)(in_vbr + 0x1f0))();
  *(uint *)(iVar1 + -0x84) = in_sr;
  *(undefined4 *)(iVar1 + -0x88) = 0x60303fe;
  (**(code **)(in_vbr + 0x1d0))();
  *(uint *)(iVar1 + -0x8c) = in_sr;
  *(undefined4 *)(iVar1 + -0x90) = 0x6030402;
  (**(code **)(in_vbr + 0x1ac))();
  *(uint *)(iVar1 + -0x94) = in_sr;
  *(undefined4 *)(iVar1 + -0x98) = 0x6030406;
  (**(code **)(in_vbr + 0x18c))();
  *(uint *)(iVar1 + -0x9c) = in_sr;
  *(undefined4 *)(iVar1 + -0xa0) = 0x603040a;
  (**(code **)(in_vbr + 0x16c))();
  *(uint *)(iVar1 + -0xa4) = in_sr;
  *(undefined4 *)(iVar1 + -0xa8) = 0x603040e;
  (**(code **)(in_vbr + 0x14c))();
  *(uint *)(iVar1 + -0xac) = in_sr;
  *(undefined4 *)(iVar1 + -0xb0) = 0x6030412;
  (**(code **)(in_vbr + 300))();
  *(uint *)(iVar1 + -0xb4) = in_sr;
  *(undefined4 *)(iVar1 + -0xb8) = 0x6030416;
  (**(code **)(in_vbr + 0x10c))();
  *(uint *)(iVar1 + -0xbc) = in_sr;
  *(undefined4 *)(iVar1 + -0xc0) = 0x603041a;
  (**(code **)(in_vbr + 0xec))();
  *(uint *)(iVar1 + -0xc4) = in_sr;
  *(undefined4 *)(iVar1 + -200) = 0x603041e;
  (**(code **)(in_vbr + 0xd0))();
  *(uint *)(iVar1 + -0xcc) = in_sr;
  *(undefined4 *)(iVar1 + -0xd0) = 0x6030422;
  (**(code **)(in_vbr + 0xb0))();
  *(uint *)(iVar1 + -0xd4) = in_sr;
  *(undefined4 *)(iVar1 + -0xd8) = 0x6030426;
  (**(code **)(in_vbr + 0x90))();
  *(uint *)(iVar1 + -0xdc) = in_sr;
  *(undefined4 *)(iVar1 + -0xe0) = 0x603042a;
  (**(code **)(in_vbr + 0x70))();
  *(uint *)(iVar1 + -0xe4) = in_sr;
  *(undefined4 *)(iVar1 + -0xe8) = 0x603042e;
  (**(code **)(in_vbr + 0x50))();
  *(uint *)(iVar1 + -0xec) = in_sr;
  *(undefined4 *)(iVar1 + -0xf0) = 0x6030432;
  (**(code **)(in_vbr + 0x34))();
  *(uint *)(iVar1 + -0xf4) = in_sr;
  *(undefined4 *)(iVar1 + -0xf8) = 0x6030436;
  uVar2 = (**(code **)(in_vbr + 0x14))();
  *(undefined4 *)(unaff_gbr + 0x3f8) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x3d8) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x3b8) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x39c) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x37c) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x360) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x344) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x324) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x308) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x2ec) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x2cc) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x2b0) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x294) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x278) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x25c) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x240) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x224) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x208) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x1ec) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x1d0) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x1b4) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x198) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x17c) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x164) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x148) = uVar2;
  *(undefined4 *)(unaff_gbr + 300) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x114) = uVar2;
  *(undefined4 *)(unaff_gbr + 0xf8) = uVar2;
  *(undefined4 *)(unaff_gbr + 0xdc) = uVar2;
  *(undefined4 *)(unaff_gbr + 0xc4) = uVar2;
  *(undefined4 *)(unaff_gbr + 0xa8) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x90) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x78) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x5c) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x44) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x2c) = uVar2;
  *(undefined4 *)(unaff_gbr + 0x10) = uVar2;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}

