/* FUN_0606DD2A  0x0606DD2A */


/* WARNING: Control flow encountered bad instruction data */

void FUN_0606dd2a(int param_1)

{
  int in_r0;
  undefined1 *puVar1;
  uint in_r1;
  undefined1 uVar2;
  uint in_r2;
  undefined4 *puVar3;
  uint uVar4;
  undefined1 *puVar5;
  undefined4 in_r3;
  uint *unaff_r8;
  int unaff_r9;
  int unaff_r10;
  undefined1 *unaff_r12;
  int unaff_r13;
  
  puVar3 = (undefined4 *)(in_r2 ^ in_r1);
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = in_r3;
  *puVar3 = puVar3;
  *puVar3 = in_r3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = puVar3;
  *puVar3 = in_r3;
  *unaff_r8 = in_r2;
  *(uint *)(unaff_r10 + 0x20) = in_r2;
  uVar4 = in_r2 ^ in_r1;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)(unaff_r10 + 8) = uVar4;
  *(uint *)(unaff_r10 + 0x28) = in_r1;
  uVar4 = (uVar4 - in_r1) - 1;
  *(undefined4 *)(unaff_r10 + 8) = in_r3;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)(param_1 + 8) = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)(param_1 + 8) = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)(unaff_r10 + 0x28) = in_r1;
  *(undefined4 *)(unaff_r10 + 8) = in_r3;
  *(uint *)(unaff_r10 + 0x28) = in_r1;
  *(undefined4 *)(unaff_r10 + 8) = in_r3;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  uVar2 = (undefined1)in_r1;
  *(undefined1 *)(unaff_r13 + in_r0) = uVar2;
  *unaff_r12 = (char)param_1;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  uVar4 = in_r0 << 0x10 | uVar4 >> 0x10;
  puVar1 = (undefined1 *)(in_r0 - 1);
  *puVar1 = (char)in_r3;
  *(uint *)uVar4 = uVar4;
  *(uint *)(param_1 + 8) = uVar4;
  puVar5 = (undefined1 *)(uVar4 - 1);
  *puVar5 = uVar2;
  *(undefined4 *)(unaff_r9 + 4) = in_r3;
  *(undefined1 **)puVar5 = puVar5;
  *(undefined1 **)puVar5 = puVar5;
  puVar5 = (undefined1 *)(uVar4 - 2);
  *puVar5 = uVar2;
  *(uint *)(param_1 + 0x3c) = in_r1;
  *(undefined1 **)puVar5 = puVar5;
  *(undefined1 **)puVar5 = puVar5;
  *(undefined1 **)puVar5 = puVar5;
  *(undefined1 **)(param_1 + 0x28) = puVar1;
  *(undefined1 **)puVar5 = puVar5;
  *(undefined1 **)puVar5 = puVar5;
  *(undefined1 **)puVar5 = puVar5;
  uVar4 = (uint)puVar5 ^ (uint)puVar1;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)uVar4 = uVar4;
  *(uint *)(unaff_r10 + 0x28) = in_r1;
  *(uint *)(unaff_r10 + 0x28) = in_r1;
  *(uint *)(unaff_r10 + 0x20) = uVar4;
  *(uint *)(unaff_r10 + 0x34) = uVar4;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}

