#!/usr/bin/env python3
"""
Generate per-function Tier-1 allowlists from the ported shims + dusa_state.h.

A pool word homed to a COL region is an ABSOLUTE LWR literal (`.long DUSA_<MACRO>
[+ 0xOFF]`) -- the LWR state block never relocates, so the assembler emits the
literal with no reloc record. check_dusa_port.py therefore can't auto-adjudicate
it; it needs a per-function allowlist entry `<func-rel offset> <expected literal>`.
race.bin symbol homes (`.long dusa_dat_* / dusa_f270_bounds`, R_SH_DIR32) and code
relocs are auto-adjudicated -> NOT allowlisted.

This derives every allowlist mechanically from the single source of truth (the
shim's COL-macro pool words + the macro addresses in dusa_state.h), so allowlists
never drift from the homing map. Owning function = the nearest dusa_<hex> label
(C entry or asm sub-label) at or above the pool word; offset = pool - func start.

  python3 tools/gen_dusa_allowlists.py            # write workstreams/.../dusa_port_allowlists/
  python3 tools/gen_dusa_allowlists.py --dry      # report only
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RACE_DIR = os.path.join(ROOT, 'mods', 'transplant', 'race')
RACE_C = os.path.join(ROOT, 'src', 'race', 'race.c')
STATE_H = os.path.join(ROOT, 'src', 'race', 'dusa_state.h')
OUT_DIR = os.path.join(ROOT, 'workstreams', 'transplant', 'dusa_port_allowlists')

FUNC_C = re.compile(r'\bint\s+(dusa_[0-9A-Fa-f]{6,8})\s*\(void\)\s*asm')
FUNC_L = re.compile(r'^\s*(dusa_[0-9A-Fa-f]{6,8})\s*:')
# `.long DUSA_<MACRO> [+ 0xOFF]   /* POOLADDR ... */`  -- a COL absolute literal.
COL_LIT = re.compile(r'^\s*\.long\s+(DUSA_\w+)(?:\s*\+\s*0x([0-9A-Fa-f]+))?\s*'
                     r'/\*\s*([0-9A-Fa-f]{6,8})\b(?P<rest>.*?)\*/')


def state_macros():
    out = {}
    for ln in open(STATE_H):
        m = re.search(r'#define\s+(DUSA_\w+)\s+(0x[0-9A-Fa-f]+)', ln)
        if m:
            out[m.group(1)] = int(m.group(2), 16)
    return out


def included_function_shims():
    inc = re.findall(r'#include "mods/transplant/race/(dusa_[0-9A-Fa-f]+)\.c"', open(RACE_C).read())
    out = []
    for name in inc:
        p = os.path.join(RACE_DIR, name + '.c')
        if os.path.isfile(p) and 'SUPERSEDED' not in open(p, encoding='utf-8').read(400):
            out.append((name, p))
    return out


def scan(macros):
    """Return {func_sym: [(offset, expected, macro, off, note)]}."""
    by_func = {}
    for _name, path in included_function_shims():
        cur = None
        for ln in open(path, encoding='utf-8'):
            m = FUNC_C.search(ln) or FUNC_L.match(ln)
            if m:
                cur = m.group(1)
                continue
            c = COL_LIT.match(ln)
            if not c or cur is None:
                continue
            macro, offhex, pool = c.group(1), c.group(2), c.group(3)
            if macro not in macros:
                raise SystemExit('%s: pool @%s uses %s not in dusa_state.h'
                                 % (path, pool, macro))
            off = int(offhex, 16) if offhex else 0
            func_addr = int(cur[5:], 16)
            rel = int(pool, 16) - func_addr
            if rel < 0:
                raise SystemExit('%s: pool @%s precedes its function %s'
                                 % (path, pool, cur))
            note = c.group('rest').strip().rstrip('-').strip() or macro
            by_func.setdefault(cur, []).append((rel, macros[macro] + off, macro, off, note))
    return by_func


def main():
    dry = '--dry' in sys.argv
    macros = state_macros()
    by_func = scan(macros)
    os.makedirs(OUT_DIR, exist_ok=True)
    for func in sorted(by_func):
        entries = sorted(by_func[func])
        lines = [
            '# Absolute COL-body literals in %s -- pool words homed to COL regions' % func,
            '# (the LWR state block never relocates -> no reloc record). GENERATED by',
            '# tools/gen_dusa_allowlists.py from the shim + dusa_state.h; do not hand-edit.',
            '# Format: <func-relative offset>  <expected literal>  # note',
        ]
        for rel, exp, macro, off, note in entries:
            lines.append('0x%03X  0x%08X   # %s%s' %
                         (rel, exp, macro, (' + 0x%X' % off) if off else ''))
        text = '\n'.join(lines) + '\n'
        path = os.path.join(OUT_DIR, '%s.txt' % func)
        if dry:
            print('=== %s.txt (%d entries) ===' % (func, len(entries)))
            print(text)
        else:
            open(path, 'w', encoding='utf-8', newline='\n').write(text)
        print('%s: %d COL literal(s)' % (func, len(entries)))
    print('\n%s%d function(s) with COL allowlists'
          % ('[dry] ' if dry else '', len(by_func)))


if __name__ == '__main__':
    main()
