#!/usr/bin/env python3
"""
gen_free_ld.py - Generate free-layout linker script from symbol registry.

Reads <module>_symbols.json (produced by resolve_pools.py) and generates
<module>_free.ld with:
  - PROVIDE(__pad_size = 0) shift mechanism
  - DAT_ symbols as function-relative offsets (shift correctly)
  - sym_ symbols as absolute addresses (don't shift)

Usage:
    python tools/gen_free_ld.py main
"""

import json
import os
import sys

PROJDIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(PROJDIR, 'src')

# Module entry points
MODULE_ENTRIES = {
    'main':     0x00280000,
    'init':     0x06000000,
    'race':     0x06000000,
    'select':   0x06000000,
    'result2p': 0x06000000,
    'name':     0x06000000,
    'backup':   0x06000000,
    'ending':   0x06000000,
}


def main():
    args = sys.argv[1:]
    if not args:
        print('Usage: python tools/gen_free_ld.py <module>')
        sys.exit(1)

    mod_name = args[0]
    if mod_name not in MODULE_ENTRIES:
        print('ERROR: unknown module "%s"' % mod_name)
        sys.exit(1)

    src_dir = os.path.join(SRC_DIR, mod_name)
    json_path = os.path.join(src_dir, '%s_symbols.json' % mod_name)
    out_path = os.path.join(src_dir, '%s_free.ld' % mod_name)

    if not os.path.isfile(json_path):
        print('ERROR: %s not found (run resolve_pools.py --write first)' % json_path)
        sys.exit(1)

    with open(json_path, 'r') as f:
        syms = json.load(f)

    mod_base = int(syms['module_base'], 16)
    dat_symbols = syms['dat_symbols']
    sym_symbols = syms['sym_symbols']

    entry = 'FUN_%08X' % mod_base

    lines = []
    lines.append('/* ================================================================')
    lines.append(' * %s_free.ld  --  Free-layout linker script for %s' % (mod_name, mod_name))
    lines.append(' *')
    lines.append(' * Functions can change size without breaking the binary.')
    lines.append(' * __pad_size shifts all FUN_ addresses to validate relocation.')
    lines.append(' *')
    lines.append(' * Usage:')
    lines.append(' *   make validate-free          # zero-shift, byte-identical')
    lines.append(' *   make disc-4shift            # +4 shift boot test')
    lines.append(' *')
    lines.append(' * Generated by gen_free_ld.py from %s_symbols.json' % mod_name)
    lines.append(' * ================================================================ */')
    lines.append('')
    lines.append('OUTPUT_FORMAT("elf32-sh")')
    lines.append('OUTPUT_ARCH(sh)')
    lines.append('ENTRY(%s)' % entry)
    lines.append('')
    lines.append('/* Default: no padding. Override with --defsym __pad_size=N */')
    lines.append('PROVIDE(__pad_size = 0);')
    lines.append('')
    lines.append('SECTIONS')
    lines.append('{')
    lines.append('    . = 0x%08X;' % mod_base)
    lines.append('')
    lines.append('    /* Pin entry function at module base so boot code can find it. */')
    lines.append('    /* It stays at the original address; its pool refs resolve to */')
    lines.append('    /* shifted targets, so the jump lands in the right place.      */')
    lines.append('    .entry : { *(.text.%s) }' % entry)
    lines.append('')
    lines.append('    .text : {')
    lines.append('        . = . + __pad_size;')
    lines.append('        *(SORT_BY_NAME(.text.FUN_*))')
    lines.append('    }')
    lines.append('')
    lines.append('    /DISCARD/ : {')
    lines.append('        *(.comment)')
    lines.append('        *(.note*)')
    lines.append('        *(.eh_frame)')
    lines.append('    }')
    lines.append('}')

    # DAT_ symbols: within-binary, relative to nearest function
    if dat_symbols:
        lines.append('')
        lines.append('/* DAT_ symbols: within-binary data, relative to nearest function (%d) */' %
                      len(dat_symbols))
        for sym_name in sorted(dat_symbols.keys()):
            info = dat_symbols[sym_name]
            parent = info['parent_fun']
            offset = int(info['offset'], 16)
            lines.append('PROVIDE(%s = %s + 0x%X);' % (sym_name, parent, offset))

    # sym_ symbols: external addresses, absolute
    if sym_symbols:
        lines.append('')
        lines.append('/* sym_ symbols: external/RAM addresses, absolute (%d) */' %
                      len(sym_symbols))
        for sym_name in sorted(sym_symbols.keys()):
            info = sym_symbols[sym_name]
            addr = int(info['absolute'], 16)
            lines.append('PROVIDE(%s = 0x%08X);' % (sym_name, addr))

    lines.append('')

    with open(out_path, 'w', newline='\n') as f:
        f.write('\n'.join(lines))

    print('Generated: %s' % out_path)
    print('  DAT_ symbols: %d (function-relative)' % len(dat_symbols))
    print('  sym_ symbols: %d (absolute)' % len(sym_symbols))


if __name__ == '__main__':
    main()
